### ISSUE TITLE
Images are attatched twice if featured

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/caldera-custom-fields#17]
cf_custom_fields_attach_file() does attatching, but so does Caldera Forms itself.

**Comment by Shelob9** [comment]
This is only going to work if Caldera Forms 1.5.0.9-b-1 or later is in use, else old behaviour applies. Thsi is beacuse I needed the change in https://github.com/CalderaWP/Caldera-Forms/issues/1516

Close via 	d43aa6f

**Comment by andrewlimaza** [comment]
@Shelob9 tested this with 1.5.0.9 and issue still exists if images uploaded to 'Save as Post Type' and the file is set as custom fields (not assigned to any field).

**Comment by Shelob9** [comment]
Still an issue after 		569964f if the image is set to attach to media library and featured image

**Comment by Shelob9** [comment]
Conceptual problem:

We're using `caldera_forms_render_setup_field` to set media library option false for featured image, which would work, IF `cf_handle_file_upload()` were called via plugins API. Which I like totally thaguht was the case beacuse: https://github.com/CalderaWP/Caldera-Forms/blob/master/includes/field_processors.php#L30-L31

But it's actually called via the upload handler https://github.com/CalderaWP/Caldera-Forms/blob/master/classes/core.php#L3417 so that filter isn't applied, #FML nothing we can do in this add-on can fix that.

**Comment by Shelob9** [comment]
Close via https://github.com/CalderaWP/Caldera-Forms/commit/a53ca7541aabc499d06e6069aa11602046b0055b and https://github.com/CalderaWP/caldera-custom-fields/commit/29f0fb9bc95fb22c2267b73ff07c670954e22bcb
