### ISSUE TITLE
PHP fatal error on image upload

### ISSUE THREAD

**Issue by Gabweb** [CalderaWP/caldera-custom-fields#18]
Tried to save a image as featured image into a custom post type. Basic Uploader throws a php fatal error. As soon as I remove the 'Save as Post Type' prosessor, the form ist able to save the image into the media library. 

`Fatal error: Uncaught ArgumentCountError: Too few arguments to function cf_custom_fields_upload_handler(), 2 passed in C:\laragon\www\B16-Test\wp-content\plugins\caldera-forms\includes\field_processors.php on line 145 and exactly 3 expected in C:\laragon\www\B16-Test\wp-content\plugins\caldera-form-metabox\includes\to-post-type.php:596 Stack trace: #0 C:\laragon\www\B16-Test\wp-content\plugins\caldera-forms\includes\field_processors.php(145): cf_custom_fields_upload_handler(Array, Array) #1 C:\laragon\www\B16-Test\wp-includes\class-wp-hook.php(298): cf_handle_file_upload('trupl59216a6e90...', Array, Array) #2 C:\laragon\www\B16-Test\wp-includes\plugin.php(203): WP_Hook->apply_filters('trupl59216a6e90...', Array) #3 C:\laragon\www\B16-Test\wp-content\plugins\caldera-forms\classes\core.php(2233): apply_filters('caldera_forms_p...', 'trupl59216a6e90...', Array, Array) #4 C:\laragon\www\B16-Test\wp-content\plugins\caldera-forms\classes\core.php(2560): Caldera_Forms::get_field_data('fld_4057893', Array, false, true) #5 C:\lara in C:\laragon\www\B16-Test\wp-content\plugins\caldera-form-metabox\includes\to-post-type.php on line 596`

WordPress 4.7.5, Caldera Custom Fields 2.1.4, Caldera Formulare 1.5.0.9

**Comment by Shelob9** [comment]
Close via  8ac12b9  Good catch @Gabweb
