### ISSUE TITLE
Feature image field saving a file when empty

### ISSUE THREAD

**Issue by New0** [CalderaWP/caldera-custom-fields#45]
Brought by https://secure.helpscout.net/conversation/517186212/7426?folderId=832038

When an image field is used to save a featured image and this field is empty, the previous file save as a featured image in the entries in saved.

**Comment by Shelob9** [comment]
Here is what is wrong: 

The featured image ID gets put in cache _after it uploads_ here:
https://github.com/CalderaWP/caldera-custom-fields/blob/master/includes/to-post-type.php#L677

Then that cached ID gets used here:
https://github.com/CalderaWP/caldera-custom-fields/blob/master/includes/to-post-type.php#L342

So, if it got written on a post with a featured image, the next post has no featured image L677 never runs so L342 has the last saved value.

**Comment by Shelob9** [comment]
Close via 
347c87a
